# 2.1 Data Manipulation

In [14]:
import torch

In [17]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [19]:
x.shape

torch.Size([12])

Number of elements(not consider axes)

In [18]:
x.numel()

12

In [20]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X = x.reshape(-1, 6)
X

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [23]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

When we construct arrays to serve as parameters in a neural network, we will typically initialize their values randomly. 

In [25]:
torch.randn((3, 4))

tensor([[-1.0588, -0.1390,  1.3607,  0.0681],
        [-0.3497, -0.0811,  1.0741,  0.4870],
        [ 0.7682,  1.3920,  0.5928,  0.2247]])

The outermost list corresponds to axis 0, and the inner list to axis 1

In [27]:
X = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

X[start:stop], the returned value includes the first index (start) but not the last (stop).

In [28]:
X[-1], X[1:3]

(tensor([4, 3, 2, 1]),
 tensor([[1, 2, 3, 4],
         [4, 3, 2, 1]]))

Modify an element in a tensor.

In [29]:
X[1, 2] = 17
X

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4],
        [ 4,  3,  2,  1]])

In [30]:
X[:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 4,  3,  2,  1]])

Binary Elementwise operations $F:(R^d,R^d)\rightarrow{R^d}$, lifting the scalar function to an elementwise vector operation

In [31]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Unary operator

In [32]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

Concatenate tensors together along axis (dim).

In [33]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

binary tensor via logical statements

In [34]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
Z = X.sum()
Z

tensor(66.)

### Broadcasting mechanism
(i) expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape; (ii) perform an elementwise operation on the resulting arrays.

In [35]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [36]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Saving memory

In [38]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [39]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1399187956016
id(Z): 1399187956016


In [40]:
before = id(Y)
Y += X
id(Y) == before

True

Convert types

In [41]:
A = X.numpy()
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [42]:
B = torch.from_numpy(A)
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [44]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)