# 2.3 Linear Algebra

In [1]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

 x = $\begin{bmatrix}x_1 \\ x_2 \\ \vdots \\ x_n \\ \end{bmatrix}$ refer to the $i^th$ element of x by $x_i$

In [6]:
x[2]

tensor(2)

In [7]:
len(x)

3

In [8]:
x.shape

torch.Size([3])

In [9]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

transpose

In [10]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [11]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

higher-order tensors

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

elementwise multiplication of two matrices is called their Hadamard product

In [13]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X)

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

calculate the sum $\sum_{i=1}^d{x_i}$

In [28]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

$\sum_{i=1}^m{\sum_{j=1}^n{a_{ij}}}$

In [16]:
A, A.sum()

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(15.))

Reducing along an axis. After that, this axis is missing from the shape of the output.

In [18]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [19]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [21]:
A.sum(axis=[0, 1]) == A.sum()# Same as `A.sum()`

tensor(True)

In [22]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

#### keep the number of axes unchanged when invoking the function for calculating the sum or mean.

In [23]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

#### divide A by sum_A with broadcasting.

In [24]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

cumulative sum of elements of A along some axis

In [26]:
A, A.cumsum(axis=0)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 5., 7.]]))

dot product $x^Ty=\sum_{i=1}^d{x_iy_i}$

In [29]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [30]:
torch.sum(x * y)

tensor(3.)

#### Matrix-Vecor dot products 
$Ax = \begin{bmatrix}a_1^T\\a_2^T\\ \vdots \\ a_n^T \end{bmatrix}x = \begin{bmatrix}a_1^T x\\a_2^Tx\\ \vdots \\ a_n^Tx \end{bmatrix}$

matrix-vector products in code with tensors, we use the mv function. When we call torch.mv(A, x) with a matrix A and a vector x, the matrix-vector product is performed

In [31]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

matrix-matrix multiplication torch.mm()

In [33]:
B = torch.ones(3, 4)
A, B, torch.mm(A, B), A@B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

$L_2 norm: \|x\|_2 = \sqrt{\sum_{i=1}^n x_i^2}$

In [34]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1 normL: \|x\|_1=\sum_{i=1}^n|x_i|$

In [35]:
torch.abs(u).sum()

tensor(7.)

#### $Frobenius norm(matrix): \|X\|_F = \sqrt{\sum_{i=1}^m\sum_{j=1}^m x_{ij}^2} $

In [36]:
torch.norm(torch.ones((4, 9)))

tensor(6.)